# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    annotations: false  # Disable annotations if not using them
    http_method_override: false  # Allow method overriding (useful for REST APIs)
    handle_all_throwables: true  # Handle all errors (you may want to change this in production)

    # Session configuration
    session:
        handler_id: null  # Default handler (file-based session storage)
        cookie_secure: auto  # Secure cookies over HTTPS only (ensure you're using HTTPS in production)
        cookie_samesite: lax  # Control cookie behavior with SameSite attribute

    # Log PHP errors
    php_errors:
        log: true

    # Environment-specific settings for testing
    when@test:
        framework:
            test: true  # Enable test-specific configuration
            session:
                storage_factory_id: session.storage.factory.mock_file  # Use mock session in tests
