
version: '3.8'

services:
  ###> database service ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
  ###< database service ###

  ###> web app (Symfony) service ###
  symfony:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"   # Exposing port 9000 to the host
    volumes:
      - .:/app    # Mount the current directory into /app inside the container
    environment:
      APP_ENV: dev   # Set to 'prod' for production environment
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}"
    depends_on:
      - database   # Ensure that the database starts before Symfony app
    command: "php -S 0.0.0.0:9000 -t public"   # Run Symfony on port 9000
  ###< web app (Symfony) service ###

volumes:
  database_data:
